const Actions = {
  // Budget
  GET_ALL_BUDGETS: "GET_ALL_BUDGETS",
  GET_BUDGET: "GET_BUDGET",
  CREATE_NEW_BUDGET: "CREATE_NEW_BUDGET",
  SET_ACTIVE_BUDGET: "SET_ACTIVE_BUDGET",
  SAVE_BUDGET: "SAVE_BUDGET",

  // Category Group
  ADD_CATEGORY_GROUP: "ADD_CATEGORY_GROUP",
  UPDATE_CATEGORY_GROUP_TITLE: "UPDATE_CATEGORY_GROUP_TITLE",

  // Category
  ADD_CATEGORY: "ADD_CATEGORY",
  UPDATE_CATEGORY_DETAILS: "UPDATE_CATEGORY_DETAILS",

  // Income Category
  DELETE_INCOME_CATEGORY: "DELETE_INCOME_CATEGORY",

  // Expense Category
  DELETE_EXPENSE_CATEGORY: "DELETE_EXPENSE_CATEGORY",

  // Expense Sub-Category
  DELETE_EXPENSE_SUB_CATEGORY: "DELETE_EXPENSE_SUB_CATEGORY",

  // Category Page
  SET_ACTIVE_CATEGORY: "SET_ACTIVE_CATEGORY",
  SAVE_CATEGORY_TO_BUDGET: "SAVE_CATEGORY_TO_BUDGET",
  RESET_CATEGORY: "RESET_CATEGORY",

  // Transaction
  UPDATE_TRANSACTION_DATE: "UPDATE_TRANSACTION_DATE",
  UPDATE_TRANSACTION_DESCRIPTION: "UPDATE_TRANSACTION_DESCRIPTION",
  UPDATE_TRANSACTION_AMOUNT: "UPDATE_TRANSACTION_AMOUNT",
  ADD_TRANSACTION: "ADD_TRANSACTION",
  DELETE_TRANSACTION: "DELETE_TRANSACTION",

  // UI
  SET_PAGE: "SET_PAGE",
  SET_EDIT: "SET_EDIT"
};

export default Actions;
