const Actions = {
  GET_ALL_BUDGETS: "GET_ALL_BUDGETS",
  GET_BUDGET: "GET_BUDGET",
  SET_ACTIVE_BUDGET: "SET_ACTIVE_BUDGET",

  UPDATE_INCOME_CATEGORY_TITLE: "UPDATE_INCOME_CATEGORY_TITLE",
  UPDATE_INCOME_CATEGORY_AMOUNT: "UPDATE_INCOME_CATEGORY_AMOUNT",
  ADD_INCOME_CATEGORY: "ADD_INCOME_CATEGORY",
  DELETE_INCOME_CATEGORY: "DELETE_INCOME_CATEGORY",

  UPDATE_EXPENSE_CATEGORY_TITLE: "UPDATE_EXPENSE_CATEGORY_TITLE",
  ADD_EXPENSE_CATEGORY: "ADD_EXPENSE_CATEGORY",
  DELETE_EXPENSE_CATEGORY: "DELETE_EXPENSE_CATEGORY",

  UPDATE_EXPENSE_SUB_CATEGORY: "UPDATE_EXPENSE_SUB_CATEGORY",
  ADD_EXPENSE_SUB_CATEGORY: "ADD_EXPENSE_SUB_CATEGORY",
  DELETE_EXPENSE_SUB_CATEGORY: "DELETE_EXPENSE_SUB_CATEGORY"
};

export default Actions;
