export const SET_ACTIVE_CATEGORY = "SET_ACTIVE_CATEGORY";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
