export const SAVE_BUDGET = "SAVE_BUDGET";
export const ADD_CATEGORY_GROUP = "ADD_CATEGORY_GROUP";
export const UPDATE_CATEGORY_GROUP_TITLE = "UPDATE_CATEGORY_GROUP_TITLE";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY_DETAILS = "UPDATE_CATEGORY_DETAILS";
export const SAVE_CATEGORY_TO_BUDGET = "SAVE_CATEGORY_TO_BUDGET";
